event:
  concurrent:
    threads: ${THREAD_COUNT}
logging:
  file:
    max-history: 4
    max-size: 10MB
    name: logs/sb-extracts.log
  level:
    org.springframework.web: ERROR
    com.am.sbextracts: INFO
pool:
  max-idle: 2
  max-total: 6
server:
  port: 9020
slack:
  token: ${TOKEN}
  verification:
    token: ${VERIFICATION_TOKEN}
  allowedUsers: ${ALLOWED_USER}
spring:
  cache:
    cache-names: conversationIds
    caffeine:
      spec: expireAfterAccess=600s

bamboo:
  apiKey: ${API_KEY}
  reportId: 1207
google:
  authJson: ${G_AUTH_JSON}
app:
  reportGFolderId: ${G_REPORT_FOLDER_ID}
  perRequestProcessingFilesCount: 400
  url: ${APP_URL}
  company:
    name: ${COMPANY_NAME}
    nsUrl: ${NS_URL}

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: none
      bambooHrSignedFile:
        connectTimeout: 20000
        readTimeout: 20000
        loggerLevel: none
