logging:
  file:
    name: logs/sb-extracts.log
  level:
    org.springframework.web: ERROR
    com.am.sbextracts: DEBUG
  logback:
    rollingpolicy:
      max-history: 4
      max-file-size: 10MB
pool:
  max-idle: 2
  max-total: 6
server:
  port: 9020
spring:
  cache:
    cache-names: conversationIds
    caffeine:
      spec: expireAfterAccess=600s

bamboo:
  reportId: 1207
app:
  perRequestProcessingFilesCount: 700

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: none
      bambooHrSignedFile:
        connectTimeout: 20000
        readTimeout: 20000
        loggerLevel: none
